version: '3.0'
services:
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: super1
    image: postgres:14.1-alpine
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080